/**
 * Digiflazz API Client
 *
 * Documentation: https://developer.digiflazz.com/
 *
 * Important Notes:
 * - Signature is calculated from: MD5(username + apiKey + command_string)
 * - Command string in signature is DIFFERENT from cmd in body!
 *
 * Command Mapping:
 * | CMD in Body | Sign from  | Endpoint         |
 * |-------------|------------|------------------|
 * | deposit     | depo       | /v1/cek-saldo    |
 * | prepaid     | pricelist  | /v1/price-list   |
 * | pasca       | pricelist  | /v1/price-list   |
 * | (topup)     | ref_id     | /v1/transaction  |
 */

const crypto = require('crypto')

// Configuration - Note: API key is loaded from proxy server, not here
const DIGIFLAZZ_PROXY_URL = process.env.DIGIFLAZZ_PROXY_URL || 'https://api.topupkilat.store'
const API_USERNAME = process.env.DIGIFLAZZ_USERNAME || 'kemikegwdEJo'

// Command to signature string mapping
const SIGNATURE_MAP: Record<string, string> = {
  'deposit': 'depo',
  'prepaid': 'pricelist',
  'pasca': 'pricelist',
}

export interface DigiflazzProduct {
  buyer_sku_code: string
  sku_code: string
  product_name: string
  category: string
  brand: string
  type: string
  price: number
  price_base: number
  margin: number
  stock: string | number
  provider: string
  uniq: string | number
  status: string
}

export interface DigiflazzBalance {
  deposit: number
}

export interface DigiflazzTopupRequest {
  buyer_sku_code: string
  customer_no: string
  ref_id: string
  testing?: boolean
  max_price?: number
  cb_url?: string
}

export interface DigiflazzTopupResponse {
  ref_id: string
  customer_no: string
  buyer_sku_code: string
  message: string
  status: 'Sukses' | 'Pending' | 'Gagal'
  rc: string
  sn?: string
  buyer_last_saldo?: number
  price?: number
}

export interface DigiflazzApiResponse<T> {
  data?: T
  rc?: string
  message?: string
}

/**
 * Generate MD5 signature for Digiflazz API
 * Format: MD5(username + apiKey + command_string)
 *
 * NOTE: This signature is used when calling the proxy.
 * The proxy will add the API key internally.
 */
function generateSignature(cmd: string, refId?: string): string {
  // For now, we generate a placeholder signature
  // The actual signature will be generated by the proxy server
  // which has the real API key

  // This is a simplified version - the proxy handles the real signature
  // We're just passing the data that the proxy needs
  return '' // Signature will be generated by proxy
}

/**
 * Make request to Digiflazz API through proxy
 * The proxy handles signature generation and API key
 */
async function digiflazzRequest<T>(
  endpoint: string,
  payload: Record<string, any>
): Promise<DigiflazzApiResponse<T>> {
  const response = await fetch(DIGIFLAZZ_PROXY_URL + endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  })

  if (!response.ok) {
    const text = await response.text()
    console.error('Digiflazz Proxy Error:', response.status, text)
    throw new Error(`Digiflazz Proxy Error: ${response.status} - ${text}`)
  }

  return response.json()
}

/**
 * Check Digiflazz account balance (deposit)
 */
export async function checkBalance(): Promise<DigiflazzBalance> {
  const sign = generateSignature('deposit')

  const response = await digiflazzRequest<DigiflazzBalance>('/', {
    cmd: 'deposit',
    username: API_USERNAME,
    sign: sign,
  })

  if (response.data?.deposit === undefined) {
    throw new Error(response.message || 'Failed to check balance')
  }

  return response.data
}

/**
 * Get price list for prepaid products
 * Filter options: code, category, brand
 */
export async function getPriceList(params?: {
  code?: string
  category?: string
  brand?: string
}): Promise<DigiflazzProduct[]> {
  const sign = generateSignature('prepaid')

  const payload: Record<string, any> = {
    cmd: 'prepaid',
    username: API_USERNAME,
    sign: sign,
  }

  // Add filters if provided
  if (params?.code) payload.code = params.code
  if (params?.category) payload.category = params.category
  if (params?.brand) payload.brand = params.brand

  const response = await digiflazzRequest<DigiflazzProduct[]>('/', payload)

  // Handle both array response and {data: [...]} response
  let data: any = response?.data
  if (Array.isArray(response)) {
    data = response
  }

  if (!data) {
    throw new Error(response?.message || 'Failed to get price list')
  }

  return data
}

/**
 * Get price list for postpaid products
 */
export async function getPostpaidPriceList(): Promise<DigiflazzProduct[]> {
  const sign = generateSignature('pasca')

  const response = await digiflazzRequest<DigiflazzProduct[]>('/', {
    cmd: 'pasca',
    username: API_USERNAME,
    sign: sign,
  })

  if (!response.data) {
    throw new Error(response.message || 'Failed to get postpaid price list')
  }

  return response.data
}

/**
 * Create topup transaction
 * For testing mode, set testing: true
 */
export async function createTopup(params: {
  buyer_sku_code: string
  customer_no: string
  ref_id: string
  testing?: boolean
}): Promise<DigiflazzTopupResponse> {
  const sign = generateSignature('topup', params.ref_id)

  const response = await digiflazzRequest<DigiflazzTopupResponse>('/', {
    cmd: 'topup',
    username: API_USERNAME,
    sign: sign,
    buyer_sku_code: params.buyer_sku_code,
    customer_no: params.customer_no,
    ref_id: params.ref_id,
    testing: params.testing || false,
  })

  if (!response.data) {
    throw new Error(response.message || 'Failed to create topup')
  }

  return response.data
}

/**
 * Verify topup status by ref_id
 */
export async function checkTopupStatus(refId: string): Promise<DigiflazzTopupResponse> {
  const sign = generateSignature('topup', refId)

  // Use same topup endpoint with the same ref_id to check status
  // Digiflazz returns the transaction status for existing ref_id
  const response = await digiflazzRequest<DigiflazzTopupResponse>('/', {
    cmd: 'topup',
    username: API_USERNAME,
    sign: sign,
    ref_id: refId,
  })

  if (!response.data) {
    throw new Error(response.message || 'Failed to check topup status')
  }

  return response.data
}

// Response codes reference
export const RC_CODES = {
  '00': 'Transaksi Sukses',
  '01': 'Transaksi Pending',
  '02': 'Transaksi Gagal',
  '03': 'Saldo tidak cukup',
  '40': 'Payload Error',
  '41': 'Signature tidak valid',
  '42': 'Username tidak cocok',
  '43': 'SKU tidak ditemukan',
  '44': 'Saldo tidak cukup',
  '45': 'IP tidak di-whitelist',
  '49': 'Ref ID tidak unik',
  '88': 'Sistem error',
}

export default {
  checkBalance,
  getPriceList,
  getPostpaidPriceList,
  createTopup,
  checkTopupStatus,
  RC_CODES,
}
